<?php

declare(strict_types=1);

namespace Sigmasoft\DataTableBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('sigmasoft_data_table');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('global_config')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('items_per_page')->defaultValue(10)->min(1)->max(100)->end()
                        ->booleanNode('enable_search')->defaultTrue()->end()
                        ->booleanNode('enable_sort')->defaultTrue()->end()
                        ->booleanNode('enable_pagination')->defaultTrue()->end()
                        ->booleanNode('enable_actions')->defaultTrue()->end()
                        ->booleanNode('enable_export')->defaultFalse()->end()
                        ->booleanNode('enable_bulk_actions')->defaultFalse()->end()
                        ->arrayNode('format_number')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->integerNode('decimal')->defaultValue(2)->end()
                                ->scalarNode('decimal_separator')->defaultValue(',')->end()
                                ->scalarNode('thousand_separator')->defaultValue(' ')->end()
                            ->end()
                        ->end()
                        ->arrayNode('format_date')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('date_format')->defaultValue('d/m/Y')->end()
                                ->scalarNode('datetime_format')->defaultValue('d/m/Y H:i')->end()
                                ->scalarNode('time_format')->defaultValue('H:i')->end()
                            ->end()
                        ->end()
                        ->arrayNode('css_classes')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('table')->defaultValue('table table-striped table-hover')->end()
                                ->scalarNode('container')->defaultValue('table-responsive')->end()
                                ->scalarNode('pagination')->defaultValue('pagination justify-content-center')->end()
                                ->scalarNode('search_input')->defaultValue('form-control')->end()
                            ->end()
                        ->end()
                        ->arrayNode('actions')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('show')->defaultTrue()->end()
                                ->booleanNode('edit')->defaultTrue()->end()
                                ->booleanNode('delete')->defaultTrue()->end()
                                ->scalarNode('show_route')->defaultNull()->end()
                                ->scalarNode('edit_route')->defaultNull()->end()
                                ->scalarNode('delete_route')->defaultNull()->end()
                            ->end()
                        ->end()
                        ->arrayNode('export')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('formats')
                                    ->scalarPrototype()->end()
                                    ->defaultValue(['csv', 'xlsx'])
                                ->end()
                                ->booleanNode('include_headers')->defaultTrue()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('entities')
                    ->useAttributeAsKey('class')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('label')->isRequired()->end()
                            ->arrayNode('fields')
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('label')->isRequired()->end()
                                        ->scalarNode('type')->defaultValue('text')->end()
                                        ->booleanNode('sortable')->defaultTrue()->end()
                                        ->booleanNode('searchable')->defaultTrue()->end()
                                        ->booleanNode('visible')->defaultTrue()->end()
                                        ->scalarNode('format')->defaultNull()->end()
                                        ->arrayNode('options')
                                            ->variablePrototype()->end()
                                        ->end()
                                        ->scalarNode('template')->defaultNull()->end()
                                        ->arrayNode('css_classes')
                                            ->scalarPrototype()->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('search_fields')
                                ->scalarPrototype()->end()
                            ->end()
                            ->arrayNode('default_sort')
                                ->children()
                                    ->scalarNode('field')->defaultNull()->end()
                                    ->enumNode('direction')->values(['asc', 'desc'])->defaultValue('asc')->end()
                                ->end()
                            ->end()
                            ->integerNode('items_per_page')->defaultNull()->end()
                            ->booleanNode('enable_search')->defaultNull()->end()
                            ->booleanNode('enable_sort')->defaultNull()->end()
                            ->booleanNode('enable_pagination')->defaultNull()->end()
                            ->booleanNode('enable_actions')->defaultNull()->end()
                            ->booleanNode('enable_export')->defaultNull()->end()
                            ->booleanNode('enable_bulk_actions')->defaultNull()->end()
                            ->arrayNode('actions')
                                ->children()
                                    ->booleanNode('show')->defaultNull()->end()
                                    ->booleanNode('edit')->defaultNull()->end()
                                    ->booleanNode('delete')->defaultNull()->end()
                                    ->scalarNode('show_route')->defaultNull()->end()
                                    ->scalarNode('edit_route')->defaultNull()->end()
                                    ->scalarNode('delete_route')->defaultNull()->end()
                                    ->arrayNode('custom')
                                        ->arrayPrototype()
                                            ->children()
                                                ->scalarNode('label')->isRequired()->end()
                                                ->scalarNode('route')->isRequired()->end()
                                                ->scalarNode('icon')->defaultNull()->end()
                                                ->scalarNode('css_class')->defaultValue('btn btn-sm btn-outline-primary')->end()
                                                ->arrayNode('route_params')
                                                    ->variablePrototype()->end()
                                                ->end()
                                                ->arrayNode('conditions')
                                                    ->variablePrototype()->end()
                                                ->end()
                                            ->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('filters')
                                ->useAttributeAsKey('name')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('type')->isRequired()->end()
                                        ->scalarNode('label')->isRequired()->end()
                                        ->scalarNode('entity')->defaultNull()->end()
                                        ->scalarNode('property')->defaultNull()->end()
                                        ->arrayNode('choices')
                                            ->variablePrototype()->end()
                                        ->end()
                                        ->arrayNode('options')
                                            ->variablePrototype()->end()
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('bulk_actions')
                                ->arrayPrototype()
                                    ->children()
                                        ->scalarNode('label')->isRequired()->end()
                                        ->scalarNode('action')->isRequired()->end()
                                        ->scalarNode('icon')->defaultNull()->end()
                                        ->scalarNode('css_class')->defaultValue('btn btn-sm btn-outline-secondary')->end()
                                        ->booleanNode('confirm')->defaultTrue()->end()
                                        ->scalarNode('confirm_message')->defaultNull()->end()
                                    ->end()
                                ->end()
                            ->end()
                            ->arrayNode('permissions')
                                ->children()
                                    ->arrayNode('view')
                                        ->scalarPrototype()->end()
                                    ->end()
                                    ->arrayNode('create')
                                        ->scalarPrototype()->end()
                                    ->end()
                                    ->arrayNode('edit')
                                        ->scalarPrototype()->end()
                                    ->end()
                                    ->arrayNode('delete')
                                        ->scalarPrototype()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('templates')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('base')->defaultValue('@SigmasoftDataTable/components/datatable/base.html.twig')->end()
                        ->scalarNode('header')->defaultValue('@SigmasoftDataTable/components/datatable/header.html.twig')->end()
                        ->scalarNode('table')->defaultValue('@SigmasoftDataTable/components/datatable/table.html.twig')->end()
                        ->scalarNode('pagination')->defaultValue('@SigmasoftDataTable/components/datatable/pagination.html.twig')->end()
                        ->scalarNode('actions')->defaultValue('@SigmasoftDataTable/components/datatable/actions.html.twig')->end()
                        ->scalarNode('filters')->defaultValue('@SigmasoftDataTable/components/datatable/filters.html.twig')->end()
                        ->scalarNode('realtime')->defaultValue('@SigmasoftDataTable/components/datatable/base_realtime.html.twig')->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}