# Configuration par défaut pour SigmasoftDataTableBundle
sigmasoft_data_table:
    defaults:
        items_per_page: 10
        enable_search: true
        enable_export: true
        export_formats: ['csv', 'excel']
        table_class: 'table table-striped table-hover'
        date_format: 'd/m/Y'
        datetime_format: 'd/m/Y H:i'
        empty_message: 'Aucune donnée disponible'
    
    templates:
        datatable: '@SigmasoftDataTable/datatable.html.twig'
        custom_templates: []
    
    caching:
        enabled: false
        ttl: 3600
    
    maker:
        auto_add_actions: true
        default_actions:
            show:
                label: 'Voir'
                icon: 'eye'
                class: 'btn btn-sm btn-info'
            edit:
                label: 'Modifier'
                icon: 'pencil'
                class: 'btn btn-sm btn-warning'
            delete:
                label: 'Supprimer'
                icon: 'trash'
                class: 'btn btn-sm btn-danger'
                confirm: true
        excluded_properties:
            - 'password'
            - 'plainPassword'
            - 'salt'
            - 'token'
            - 'resetToken'
            - 'confirmationToken'
        default_column_types:
            string: 'text'
            text: 'text'
            integer: 'text'
            float: 'text'
            decimal: 'text'
            boolean: 'badge'
            datetime: 'date'
            datetime_immutable: 'date'
            date: 'date'
            date_immutable: 'date'
            time: 'date'
            time_immutable: 'date'