# src/SigmasoftDataTableBundle/Resources/config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sigmasoft\DataTableBundle\Service\DataTableServiceInterface:
        alias: Sigmasoft\DataTableBundle\Service\DataTableService

    Sigmasoft\DataTableBundle\Service\DataTableService:
        arguments:
            $allowedEntities: '%sigmasoft_data_table.allowed_entities%'

    Sigmasoft\DataTableBundle\Service\ValueFormatter:
        arguments:
            $defaultConfig: '%sigmasoft_data_table.default_config%'

    Sigmasoft\DataTableBundle\Twig\Components\SigmasoftDataTableComponent:
        tags:
            - { name: twig.component, key: 'SigmasoftDataTable' }

    # Commande Maker pour génération automatique
    Sigmasoft\DataTableBundle\Maker\MakeDataTable:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: maker.command }