<?php

/**
 * Configuration - Configuration YAML du SigmasoftDataTableBundle
 * 
 * @author Gédeon Makela <g.makela@sigmasoft-solution.com>
 * @copyright 2024 Sigmasoft Solution
 * @package Sigmasoft\DataTableBundle\DependencyInjection
 */

declare(strict_types=1);

namespace Sigmasoft\DataTableBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('sigmasoft_data_table');
        $rootNode = $treeBuilder->getRootNode();

        $rootNode
            ->children()
                ->arrayNode('defaults')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('items_per_page')
                            ->defaultValue(10)
                            ->min(1)
                            ->max(500)
                        ->end()
                        ->booleanNode('enable_search')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('enable_pagination')
                            ->defaultValue(true)
                        ->end()
                        ->booleanNode('enable_sorting')
                            ->defaultValue(true)
                        ->end()
                        ->scalarNode('table_class')
                            ->defaultValue('table table-striped table-hover align-middle')
                        ->end()
                        ->scalarNode('date_format')
                            ->defaultValue('d/m/Y')
                        ->end()
                        ->arrayNode('pagination_sizes')
                            ->defaultValue([5, 10, 25, 50, 100])
                            ->integerPrototype()->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('templates')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('datatable')
                            ->defaultValue('@SigmasoftDataTable/datatable.html.twig')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('caching')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultValue(false)
                        ->end()
                        ->integerNode('ttl')
                            ->defaultValue(3600)
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('maker')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('default_column_types')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('string')
                                    ->defaultValue('text')
                                ->end()
                                ->scalarNode('text')
                                    ->defaultValue('text')
                                ->end()
                                ->scalarNode('integer')
                                    ->defaultValue('text')
                                ->end()
                                ->scalarNode('float')
                                    ->defaultValue('text')
                                ->end()
                                ->scalarNode('decimal')
                                    ->defaultValue('text')
                                ->end()
                                ->scalarNode('boolean')
                                    ->defaultValue('badge')
                                ->end()
                                ->scalarNode('datetime')
                                    ->defaultValue('date')
                                ->end()
                                ->scalarNode('datetime_immutable')
                                    ->defaultValue('date')
                                ->end()
                                ->scalarNode('date')
                                    ->defaultValue('date')
                                ->end()
                                ->scalarNode('date_immutable')
                                    ->defaultValue('date')
                                ->end()
                                ->scalarNode('time')
                                    ->defaultValue('date')
                                ->end()
                                ->scalarNode('time_immutable')
                                    ->defaultValue('date')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('excluded_properties')
                            ->defaultValue(['password', 'plainPassword', 'salt', 'token', 'resetToken'])
                            ->scalarPrototype()->end()
                        ->end()
                        ->booleanNode('auto_add_actions')
                            ->defaultValue(true)
                        ->end()
                        ->arrayNode('default_actions')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('show')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('icon')
                                            ->defaultValue('bi bi-eye')
                                        ->end()
                                        ->scalarNode('class')
                                            ->defaultValue('btn btn-sm btn-info')
                                        ->end()
                                        ->scalarNode('title')
                                            ->defaultValue('Voir')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('edit')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('icon')
                                            ->defaultValue('bi bi-pencil-square')
                                        ->end()
                                        ->scalarNode('class')
                                            ->defaultValue('btn btn-sm btn-warning')
                                        ->end()
                                        ->scalarNode('title')
                                            ->defaultValue('Modifier')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('delete')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('type')
                                            ->defaultValue('delete')
                                        ->end()
                                        ->scalarNode('icon')
                                            ->defaultValue('bi bi-trash')
                                        ->end()
                                        ->scalarNode('class')
                                            ->defaultValue('btn btn-sm btn-danger')
                                        ->end()
                                        ->scalarNode('title')
                                            ->defaultValue('Supprimer')
                                        ->end()
                                        ->scalarNode('confirm')
                                            ->defaultValue('Êtes-vous sûr de vouloir supprimer cet élément ?')
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
