# Configuration par défaut du SigmasoftDataTableBundle
# Documentation complète: https://chancel18.github.io/SigmasoftDataTableBundle/

sigmasoft_data_table:
    # Configuration par défaut des DataTables
    defaults:
        items_per_page: 10                          # Nombre d'éléments par page
        enable_search: true                         # Activer la recherche globale
        enable_pagination: true                     # Activer la pagination
        enable_sorting: true                        # Activer le tri des colonnes
        table_class: 'table table-striped table-hover' # Classes CSS Bootstrap
        date_format: 'd/m/Y'                       # Format d'affichage des dates
        pagination_sizes: [5, 10, 25, 50, 100]    # Options de pagination
        
    # Configuration des templates Twig (optionnel)
    templates:
        datatable: '@SigmasoftDataTable/datatable.html.twig'
        
    # Configuration du cache (recommandé en production)
    caching:
        enabled: '%env(bool:SIGMASOFT_DATATABLE_CACHE_ENABLED)%'
        ttl: 3600                                   # Durée de vie en secondes
        
    # Configuration du Maker Command
    maker:
        default_column_types:
            string: 'text'
            text: 'text' 
            integer: 'text'
            boolean: 'badge'
            datetime: 'date'
            date: 'date'